name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Networking Tests
      run: dotnet test --filter "FullyQualifiedName~Testing.Networking" --no-build --verbosity normal  
    - name: UX Tests
      run: dotnet test --filter "FullyQualifiedName~Testing.UX" --no-build --verbosity normal
    - name: ScreenSharing Tests
      run: dotnet test --filter "FullyQualifiedName~Testing.ScreenSharing" --no-build --verbosity normal
    - name: Dashboard Tests
      run: dotnet test --filter "FullyQualifiedName~Testing.Dashboard" --no-build --verbosity normal
    - name: Content Tests
      run: dotnet test --filter "FullyQualifiedName~Testing.Content" --no-build --verbosity normal
    - name: Whiteboard Tests
      run: dotnet test --filter "FullyQualifiedName~Testing.Whiteboard" --no-build --verbosity normal
    - name: E2E Tests
      run: dotnet test --filter "FullyQualifiedName~Testing.E2E" --no-build --verbosity normal
